'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { parseSql } = require('../src/parser');
const { diffSchemas, formatDiff, normalizeType } = require('../src/diff');

// Одна и та же схема: как пишут руками и как её отдаёт PostgreSQL (мост к базе).
const HANDWRITTEN = `
CREATE TYPE status AS ENUM ('new', 'done');
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  role TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('student', 'admin')),
  created TIMESTAMPTZ NOT NULL DEFAULT now(),
  score NUMERIC(10, 2) DEFAULT 0,
  active BOOL NOT NULL DEFAULT TRUE
);
CREATE TABLE tasks (
  id BIGSERIAL PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users,
  st status NOT NULL DEFAULT 'new',
  UNIQUE (user_id, st)
);
CREATE INDEX idx_tasks_user ON tasks (user_id);
CREATE UNIQUE INDEX idx_users_email_lower ON users (lower(email)) WHERE active;
`;

const FROM_DB = `
CREATE TYPE public.status AS ENUM ('new', 'done');
CREATE TABLE public.users (
    id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    email character varying(255) NOT NULL,
    role text NOT NULL DEFAULT 'student'::text,
    created timestamp with time zone NOT NULL DEFAULT now(),
    score numeric(10,2) DEFAULT (0)::numeric,
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_role_check CHECK ((role = ANY (ARRAY['student'::text, 'admin'::text])))
);
CREATE TABLE public.tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    st status NOT NULL DEFAULT 'new'::status,
    CONSTRAINT tasks_user_id_st_key UNIQUE (user_id, st),
    CONSTRAINT tasks_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_tasks_user ON public.tasks USING btree (user_id);
CREATE UNIQUE INDEX idx_users_email_lower ON public.users USING btree (lower((email)::text)) WHERE active;
`;

test('синонимы типов', () => {
  assert.equal(normalizeType('INT'), 'integer');
  assert.equal(normalizeType('SERIAL'), 'integer');
  assert.equal(normalizeType('character varying(255)'), 'varchar(255)');
  assert.equal(normalizeType('TIMESTAMP WITH TIME ZONE'), 'timestamptz');
  assert.equal(normalizeType('NUMERIC(10, 2)'), 'numeric(10,2)');
  assert.equal(normalizeType('public.status[]'), 'status[]');
  assert.equal(normalizeType('bool'), 'boolean');
});

test('одна схема в двух записях — различий нет', () => {
  const d = diffSchemas(parseSql(HANDWRITTEN), parseSql(FROM_DB));
  assert.equal(d.count, 0, formatDiff(d));
  assert.deepEqual(d.same.sort(), ['tasks', 'users']);
});

test('различия: колонки, типы, NOT NULL, DEFAULT, ключи, индексы, ENUM, таблицы', () => {
  const diagram = parseSql(HANDWRITTEN.replace('score NUMERIC(10, 2) DEFAULT 0,', 'score NUMERIC(12, 2) NOT NULL DEFAULT 1, nick TEXT,')
    + 'CREATE TABLE notes (id INT PRIMARY KEY, body TEXT);');
  const db = parseSql(FROM_DB
    .replace("('new', 'done')", "('new', 'done', 'failed')")
    .replace('CREATE INDEX idx_tasks_user ON public.tasks USING btree (user_id);', '')
    + 'CREATE TABLE public.audit (id integer PRIMARY KEY);');
  const d = diffSchemas(diagram, db);
  const report = formatDiff(d);

  assert.deepEqual(d.onlyLeft, ['notes']);
  assert.deepEqual(d.onlyRight, ['audit']);
  const users = d.changed.find(t => t.name === 'users').changes.map(c => c.text);
  assert.ok(users.includes('score: тип — на диаграмме numeric(12,2), в схеме numeric(10,2)'), report);
  assert.ok(users.includes('score: на диаграмме NOT NULL, в схеме нет'), report);
  assert.ok(users.includes('score: DEFAULT — на диаграмме 1, в схеме 0'), report);
  assert.ok(users.includes('колонка nick: только на диаграмме'), report);
  const tasks = d.changed.find(t => t.name === 'tasks').changes.map(c => c.text);
  assert.ok(tasks.some(t => /индекс idx_tasks_user \(user_id\): только на диаграмме/.test(t)), report);
  assert.match(d.enums[0].text, /ENUM status: значения/);
  assert.match(report, /➕ Только в схеме[\s\S]*audit/);
});

test('подсказка о переименовании таблицы и «возможно отличается» для CHECK', () => {
  const diagram = parseSql('CREATE TABLE app_users (id INT PRIMARY KEY, email TEXT, name TEXT); CREATE TABLE t (x INT CHECK (x BETWEEN 1 AND 5));');
  const db = parseSql('CREATE TABLE users (id INT PRIMARY KEY, email TEXT, name TEXT); CREATE TABLE t (x INT CHECK (x >= 1 AND x <= 5));');
  const d = diffSchemas(diagram, db);
  assert.deepEqual(d.hints, ['возможно, таблица переименована: users → app_users']);
  assert.ok(d.changed.find(t => t.name === 't').changes.every(c => c.maybe));
});

test('комментарии сравниваются только по галочке', () => {
  const a = parseSql("CREATE TABLE t (id INT); COMMENT ON TABLE t IS 'x';");
  const b = parseSql('CREATE TABLE t (id INT);');
  assert.equal(diffSchemas(a, b).count, 0);
  assert.equal(diffSchemas(a, b, { comments: true }).count, 1);
});
