'use strict';

// Чтение структуры PostgreSQL из системного каталога и сборка DDL
// (CREATE TABLE / CREATE INDEX), который дальше разбирает тот же parser.js.
// Работает только на чтение: выполняются одни SELECT по pg_catalog.

const TABLES_SQL = `
  SELECT c.oid, n.nspname AS schema, c.relname AS name,
         format('%I.%I', n.nspname, c.relname) AS qualified
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE c.relkind IN ('r', 'p')
    AND NOT c.relispartition
    AND n.nspname = ANY($1::text[])
  ORDER BY n.nspname, c.relname`;

const COLUMNS_SQL = `
  SELECT a.attrelid AS table_oid, a.attnum, quote_ident(a.attname) AS name,
         format_type(a.atttypid, a.atttypmod) AS type,
         a.attnotnull AS not_null,
         pg_get_expr(d.adbin, d.adrelid) AS default_expr,
         a.attidentity AS identity,
         to_jsonb(a) ->> 'attgenerated' AS generated
  FROM pg_attribute a
  LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
  WHERE a.attrelid = ANY($1::oid[]) AND a.attnum > 0 AND NOT a.attisdropped
  ORDER BY a.attrelid, a.attnum`;

const CONSTRAINTS_SQL = `
  SELECT conrelid AS table_oid, quote_ident(conname) AS name, contype AS type,
         conkey AS columns, pg_get_constraintdef(oid, true) AS def
  FROM pg_constraint
  WHERE conrelid = ANY($1::oid[]) AND contype IN ('p', 'u', 'f', 'c', 'x')
  ORDER BY conrelid, CASE contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'f' THEN 2 ELSE 3 END, conname`;

// Индексы, созданные вручную (без тех, что PostgreSQL сделал сам под PK/UNIQUE/EXCLUDE).
const INDEXES_SQL = `
  SELECT i.indrelid AS table_oid, pg_get_indexdef(i.indexrelid) AS def
  FROM pg_index i
  JOIN pg_class ic ON ic.oid = i.indexrelid
  WHERE i.indrelid = ANY($1::oid[])
    AND NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conindid = i.indexrelid AND c.contype IN ('p', 'u', 'x'))
  ORDER BY i.indrelid, ic.relname`;

const SERIAL_TYPES = { smallint: 'smallserial', integer: 'serial', bigint: 'bigserial' };

// PostgreSQL хранит выражения в нормализованном виде — возвращаем их к тому,
// как их обычно пишут:
//   (status)::text = ANY ((ARRAY['a'::character varying, 'b'])::text[])  →  status IN ('a', 'b')
//   'draft'::text → 'draft',   (0)::numeric → 0,   CHECK ((x > 0)) → CHECK (x > 0)
const TEXT_TYPES = '(?:text|character varying|varchar|bpchar|character)';
const NUMERIC_TYPES = '(?:numeric|integer|bigint|smallint|real|double precision)';

function simplifyExpr(expr) {
  if (!expr) return expr;
  let s = expr;
  s = s.replace(new RegExp(`\\(\\(ARRAY\\[([^\\]]*)\\]\\)::${TEXT_TYPES}\\[\\]\\)`, 'g'), '(ARRAY[$1])');
  s = s.replace(new RegExp(`'((?:[^']|'')*)'::${TEXT_TYPES}(?![\\w\\[])`, 'g'), "'$1'");
  s = s.replace(new RegExp(`\\(([A-Za-z_][\\w$]*|"(?:[^"]|"")+")\\)::${TEXT_TYPES}(?![\\w\\[])`, 'g'), '$1');
  s = s.replace(new RegExp(`\\((-?\\d+(?:\\.\\d+)?)\\)::${NUMERIC_TYPES}\\b`, 'g'), '$1');
  s = s.replace(new RegExp(`(^|[^\\w.'])(\\d+(?:\\.\\d+)?)::${NUMERIC_TYPES}\\b`, 'g'), '$1$2');
  // «x = ANY (ARRAY[…])» и «x = ANY ((ARRAY[…]))» — скобки учитываем парами.
  const list = '(?:\\(ARRAY\\[([^\\]]*)\\]\\)|ARRAY\\[([^\\]]*)\\])';
  const ident = '([A-Za-z_][\\w$.]*|"(?:[^"]|"")+")';
  s = s.replace(new RegExp(`${ident}\\s*=\\s*ANY\\s*\\(\\s*${list}\\s*\\)`, 'g'),
    (m, col, a, b) => `${col} IN (${a !== undefined ? a : b})`);
  s = s.replace(new RegExp(`${ident}\\s*<>\\s*ALL\\s*\\(\\s*${list}\\s*\\)`, 'g'),
    (m, col, a, b) => `${col} NOT IN (${a !== undefined ? a : b})`);
  return stripOuterParens(s);
}

// «CHECK ((a > 0))» → «CHECK (a > 0)»; «((a > 0))» → «(a > 0)».
function stripOuterParens(s) {
  const m = /^(CHECK\s*)?\((.*)\)$/s.exec(s);
  if (!m) return s;
  let inner = m[2];
  while (inner.startsWith('(') && inner.endsWith(')') && balanced(inner.slice(1, -1))) inner = inner.slice(1, -1);
  return (m[1] ? m[1] : '') + '(' + inner + ')';
}

function balanced(s) {
  let depth = 0;
  let quote = false;
  for (const ch of s) {
    if (ch === "'") quote = !quote;
    if (quote) continue;
    if (ch === '(') depth++;
    if (ch === ')' && --depth < 0) return false;
  }
  return depth === 0;
}

// Колонка в виде «имя тип ограничения…», как её обычно пишут руками.
function columnDdl(col, inline) {
  let type = col.type;
  let defaultExpr = simplifyExpr(col.default_expr);
  let notNull = col.not_null;
  const parts = [];

  // integer + DEFAULT nextval('…_seq'::regclass) → serial (так выглядит исходный DDL).
  if (defaultExpr && /^nextval\('[^']+'::regclass\)$/.test(defaultExpr) && SERIAL_TYPES[type]) {
    type = SERIAL_TYPES[type];
    defaultExpr = null;
    notNull = false; // serial и так NOT NULL
  }

  if (col.identity === 'a') parts.push('GENERATED ALWAYS AS IDENTITY');
  else if (col.identity === 'd') parts.push('GENERATED BY DEFAULT AS IDENTITY');

  const isPk = inline.some(c => c.type === 'p');
  if (notNull && !isPk && !col.identity) parts.push('NOT NULL');

  if (col.generated === 's' && defaultExpr) parts.push(`GENERATED ALWAYS AS (${defaultExpr}) STORED`);
  else if (defaultExpr) parts.push('DEFAULT ' + defaultExpr);

  for (const c of inline) {
    if (c.type === 'p') parts.push('PRIMARY KEY');
    else if (c.type === 'u') parts.push('UNIQUE');
    else if (c.type === 'f') parts.push(c.def.replace(/^FOREIGN KEY \([^)]*\)\s*/, ''));
    else if (c.type === 'c') parts.push(simplifyExpr(c.def));
  }

  return [col.name, type, ...parts].join(' ');
}

// rows: { tables, columns, constraints, indexes } — строки из запросов выше.
function buildDdl({ tables, columns, constraints, indexes }) {
  const out = [];
  for (const table of tables) {
    const oid = String(table.oid);
    const cols = columns.filter(c => String(c.table_oid) === oid);
    const cons = constraints.filter(c => String(c.table_oid) === oid);

    // Ограничения на одну колонку пишем в строке колонки, остальные — отдельно.
    const inlineFor = new Map(cols.map(c => [c.attnum, []]));
    const tableLevel = [];
    for (const con of cons) {
      const keys = (con.columns || []).map(Number);
      if (keys.length === 1 && con.type !== 'x' && inlineFor.has(keys[0])) inlineFor.get(keys[0]).push(con);
      else tableLevel.push(`CONSTRAINT ${con.name} ${con.type === 'c' ? simplifyExpr(con.def) : con.def}`);
    }

    const lines = cols.map(c => '    ' + columnDdl(c, inlineFor.get(c.attnum)));
    tableLevel.forEach(def => lines.push('    ' + def));
    out.push(`CREATE TABLE ${table.qualified} (\n${lines.join(',\n')}\n);`);

    for (const ix of indexes.filter(i => String(i.table_oid) === oid)) out.push(simplifyExpr(ix.def) + ';');
    out.push('');
  }
  return out.join('\n');
}

// Подключается, читает каталог и возвращает { sql, tables }.
async function introspect(connectionString, schemas = ['public']) {
  let pg;
  try {
    pg = require('pg');
  } catch {
    throw new Error('Не установлен драйвер PostgreSQL. В папке проекта выполните: npm install');
  }

  const client = new pg.Client({ connectionString, connectionTimeoutMillis: 10000 });
  await client.connect();
  try {
    await client.query('SET default_transaction_read_only = on');
    const tables = (await client.query(TABLES_SQL, [schemas])).rows;
    if (!tables.length) {
      return { sql: '', tables: 0, message: `В схемах ${schemas.join(', ')} нет таблиц` };
    }
    const oids = tables.map(t => t.oid);
    const columns = await client.query(COLUMNS_SQL, [oids]);
    const constraints = await client.query(CONSTRAINTS_SQL, [oids]);
    const indexes = await client.query(INDEXES_SQL, [oids]);
    const sql = buildDdl({ tables, columns: columns.rows, constraints: constraints.rows, indexes: indexes.rows });
    return { sql, tables: tables.length };
  } finally {
    await client.end();
  }
}

module.exports = { introspect, buildDdl, columnDdl, simplifyExpr };
