'use strict';

// Чтение структуры PostgreSQL из системного каталога и сборка DDL
// (CREATE TABLE / CREATE INDEX), который дальше разбирает тот же parser.js.
// Работает только на чтение: выполняются одни SELECT по pg_catalog.

const { simplifyExpr } = require('../src/sqltext');

const TABLES_SQL = `
  SELECT c.oid, n.nspname AS schema, c.relname AS name,
         format('%I.%I', n.nspname, c.relname) AS qualified,
         obj_description(c.oid, 'pg_class') AS comment
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE c.relkind IN ('r', 'p')
    AND NOT c.relispartition
    AND n.nspname = ANY($1::text[])
  ORDER BY n.nspname, c.relname`;

const COLUMNS_SQL = `
  SELECT a.attrelid AS table_oid, a.attnum, quote_ident(a.attname) AS name,
         format_type(a.atttypid, a.atttypmod) AS type,
         a.attnotnull AS not_null,
         pg_get_expr(d.adbin, d.adrelid) AS default_expr,
         a.attidentity AS identity,
         to_jsonb(a) ->> 'attgenerated' AS generated,
         col_description(a.attrelid, a.attnum) AS comment
  FROM pg_attribute a
  LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
  WHERE a.attrelid = ANY($1::oid[]) AND a.attnum > 0 AND NOT a.attisdropped
  ORDER BY a.attrelid, a.attnum`;

const CONSTRAINTS_SQL = `
  SELECT conrelid AS table_oid, quote_ident(conname) AS name, contype AS type,
         conkey AS columns, pg_get_constraintdef(oid, true) AS def
  FROM pg_constraint
  WHERE conrelid = ANY($1::oid[]) AND contype IN ('p', 'u', 'f', 'c', 'x')
  ORDER BY conrelid, CASE contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'f' THEN 2 ELSE 3 END, conname`;

// Индексы, созданные вручную (без тех, что PostgreSQL сделал сам под PK/UNIQUE/EXCLUDE).
const INDEXES_SQL = `
  SELECT i.indrelid AS table_oid, pg_get_indexdef(i.indexrelid) AS def
  FROM pg_index i
  JOIN pg_class ic ON ic.oid = i.indexrelid
  WHERE i.indrelid = ANY($1::oid[])
    AND NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conindid = i.indexrelid AND c.contype IN ('p', 'u', 'x'))
  ORDER BY i.indrelid, ic.relname`;

// Перечисления (ENUM) со значениями в их порядке.
const ENUMS_SQL = `
  SELECT t.oid, format('%I.%I', n.nspname, t.typname) AS qualified,
         obj_description(t.oid, 'pg_type') AS comment,
         array_agg(e.enumlabel::text ORDER BY e.enumsortorder) AS labels
  FROM pg_type t
  JOIN pg_namespace n ON n.oid = t.typnamespace
  JOIN pg_enum e ON e.enumtypid = t.oid
  WHERE n.nspname = ANY($1::text[])
  GROUP BY t.oid, n.nspname, t.typname
  ORDER BY n.nspname, t.typname`;

// Представления и материализованные представления: текст запроса и имена колонок.
const VIEWS_SQL = `
  SELECT c.oid, c.relkind AS kind, format('%I.%I', n.nspname, c.relname) AS qualified,
         pg_get_viewdef(c.oid, true) AS def,
         obj_description(c.oid, 'pg_class') AS comment,
         (SELECT array_agg(quote_ident(a.attname) ORDER BY a.attnum)
            FROM pg_attribute a
           WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped) AS columns
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE c.relkind IN ('v', 'm') AND n.nspname = ANY($1::text[])
  ORDER BY n.nspname, c.relname`;

const sqlString = text => "'" + String(text).replace(/'/g, "''") + "'";

function stripEnumCasts(text, enums) {
  let out = text;
  for (const en of enums) {
    const name = en.qualified.split('.').pop().replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    out = out.replace(new RegExp(`('(?:[^']|'')*')::(?:[\\w"]+\\.)?${name}(\\[\\])?(?![\\w])`, 'g'), '$1');
  }
  return out;
}

const SERIAL_TYPES = { smallint: 'smallserial', integer: 'serial', bigint: 'bigserial' };


// Колонка в виде «имя тип ограничения…», как её обычно пишут руками.
function columnDdl(col, inline) {
  let type = col.type;
  let defaultExpr = simplifyExpr(col.default_expr);
  let notNull = col.not_null;
  const parts = [];

  // integer + DEFAULT nextval('…_seq'::regclass) → serial (так выглядит исходный DDL).
  if (defaultExpr && /^nextval\('[^']+'::regclass\)$/.test(defaultExpr) && SERIAL_TYPES[type]) {
    type = SERIAL_TYPES[type];
    defaultExpr = null;
    notNull = false; // serial и так NOT NULL
  }

  if (col.identity === 'a') parts.push('GENERATED ALWAYS AS IDENTITY');
  else if (col.identity === 'd') parts.push('GENERATED BY DEFAULT AS IDENTITY');

  const isPk = inline.some(c => c.type === 'p');
  if (notNull && !isPk && !col.identity) parts.push('NOT NULL');

  if (col.generated === 's' && defaultExpr) parts.push(`GENERATED ALWAYS AS (${defaultExpr}) STORED`);
  else if (defaultExpr) parts.push('DEFAULT ' + defaultExpr);

  for (const c of inline) {
    if (c.type === 'p') parts.push('PRIMARY KEY');
    else if (c.type === 'u') parts.push('UNIQUE');
    else if (c.type === 'f') parts.push(c.def.replace(/^FOREIGN KEY \([^)]*\)\s*/, ''));
    else if (c.type === 'c') parts.push(simplifyExpr(c.def));
  }

  return [col.name, type, ...parts].join(' ');
}

// Одинаковые ограничения (тот же тип, те же колонки, то же определение) под разными именами.
// Так бывает, например, из-за ALTER TABLE … ADD COLUMN IF NOT EXISTS … CHECK (…) при каждом
// запуске миграции: колонку PostgreSQL пропускает, а CHECK добавляет снова (users_role_check1, 2, …).
const constraintKey = c => [c.table_oid, c.type, (c.columns || []).join(','), c.def].join('\u0000');

// Сообщения о дублях: «users: одинаковое ограничение CHECK (…) повторяется 52 раза (users_role_check, …)».
function duplicateConstraints({ tables, constraints }) {
  const groups = new Map();
  for (const c of constraints) {
    const key = constraintKey(c);
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(c);
  }
  const messages = [];
  for (const group of groups.values()) {
    if (group.length < 2) continue;
    const table = tables.find(t => String(t.oid) === String(group[0].table_oid));
    const names = group.map(c => c.name);
    const shown = names.length > 3 ? `${names.slice(0, 3).join(', ')}, …` : names.join(', ');
    messages.push(`${table ? table.name : '?'}: одинаковое ограничение ${simplifyExpr(group[0].def)} ` +
      `повторяется ${times(group.length)} (${shown})`);
  }
  return messages;
}

// 1 раз, 2–4 раза, 5–20 раз, 21 раз, 22 раза…
function times(n) {
  const mod10 = n % 10;
  const mod100 = n % 100;
  const word = mod10 >= 2 && mod10 <= 4 && (mod100 < 12 || mod100 > 14) ? 'раза' : 'раз';
  return n + ' ' + word;
}

// rows: { tables, columns, constraints, indexes } — строки из запросов выше.
function buildDdl({ tables, columns, constraints, indexes, enums = [], views = [] }) {
  const out = [];
  for (const en of enums) {
    out.push(`CREATE TYPE ${en.qualified} AS ENUM (${(en.labels || []).map(sqlString).join(', ')});`);
  }
  if (enums.length) out.push('');
  for (const table of tables) {
    const oid = String(table.oid);
    const cols = columns.filter(c => String(c.table_oid) === oid);
    // Все ограничения — как в базе, в том числе дубли (о них — предупреждение, см. duplicateConstraints).
    const cons = constraints.filter(c => String(c.table_oid) === oid);

    // Ограничения на одну колонку пишем в строке колонки, остальные — отдельно.
    const inlineFor = new Map(cols.map(c => [c.attnum, []]));
    const tableLevel = [];
    for (const con of cons) {
      const keys = (con.columns || []).map(Number);
      if (keys.length === 1 && con.type !== 'x' && inlineFor.has(keys[0])) inlineFor.get(keys[0]).push(con);
      else tableLevel.push(`CONSTRAINT ${con.name} ${con.type === 'c' ? simplifyExpr(con.def) : con.def}`);
    }

    // 'new'::order_status → 'new' (приведение к своему ENUM в значениях по умолчанию лишнее).
    const lines = cols.map(c => '    ' + stripEnumCasts(columnDdl(c, inlineFor.get(c.attnum)), enums));
    tableLevel.forEach(def => lines.push('    ' + def));
    out.push(`CREATE TABLE ${table.qualified} (\n${lines.join(',\n')}\n);`);

    for (const ix of indexes.filter(i => String(i.table_oid) === oid)) out.push(simplifyExpr(ix.def) + ';');
    out.push('');
  }

  for (const v of views) {
    const kind = v.kind === 'm' ? 'MATERIALIZED VIEW' : 'VIEW';
    const cols = v.columns && v.columns.length ? ` (${v.columns.join(', ')})` : '';
    out.push(`CREATE ${kind} ${v.qualified}${cols} AS\n${String(v.def || '').trim().replace(/;\s*$/, '')};`);
    out.push('');
  }

  // Комментарии — отдельными COMMENT ON, как в pg_dump.
  const comments = [];
  for (const en of enums) if (en.comment) comments.push(`COMMENT ON TYPE ${en.qualified} IS ${sqlString(en.comment)};`);
  for (const t of tables) {
    if (t.comment) comments.push(`COMMENT ON TABLE ${t.qualified} IS ${sqlString(t.comment)};`);
    for (const c of columns.filter(col => String(col.table_oid) === String(t.oid) && col.comment)) {
      comments.push(`COMMENT ON COLUMN ${t.qualified}.${c.name} IS ${sqlString(c.comment)};`);
    }
  }
  for (const v of views) {
    if (v.comment) comments.push(`COMMENT ON ${v.kind === 'm' ? 'MATERIALIZED VIEW' : 'VIEW'} ${v.qualified} IS ${sqlString(v.comment)};`);
  }
  out.push(...comments);
  return out.join('\n');
}

// Подключается, читает каталог и возвращает { sql, tables }.
async function introspect(connectionString, schemas = ['public']) {
  let pg;
  try {
    pg = require('pg');
  } catch {
    throw new Error('Не установлен драйвер PostgreSQL. В папке проекта выполните: npm install');
  }

  const client = new pg.Client({ connectionString, connectionTimeoutMillis: 10000 });
  await client.connect();
  try {
    await client.query('SET default_transaction_read_only = on');
    const tables = (await client.query(TABLES_SQL, [schemas])).rows;
    const enums = (await client.query(ENUMS_SQL, [schemas])).rows;
    const views = (await client.query(VIEWS_SQL, [schemas])).rows;
    if (!tables.length && !views.length) {
      return { sql: '', tables: 0, message: `В схемах ${schemas.join(', ')} нет таблиц` };
    }
    const oids = tables.map(t => t.oid);
    const columns = await client.query(COLUMNS_SQL, [oids]);
    const constraints = await client.query(CONSTRAINTS_SQL, [oids]);
    const indexes = await client.query(INDEXES_SQL, [oids]);
    const catalog = {
      tables, columns: columns.rows, constraints: constraints.rows, indexes: indexes.rows, enums, views
    };
    return { sql: buildDdl(catalog), tables: tables.length, warnings: duplicateConstraints(catalog) };
  } finally {
    await client.end();
  }
}

module.exports = { introspect, buildDdl, columnDdl, simplifyExpr, duplicateConstraints };
